### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by solaimanjdn**

### CODE REVIEW

**Comment by olmobrutall** [comment]
Hi solaimanjdn, thanks for the pull request! 

I assume that FlowDirection and Unicode SQL are some localization issues for RTL languages. Could you elaborate on that? 

Im more surprised on the default SQL command. What's going on there? It usually works...

Finally, I would like to discuss the CloseForm functionality. It know it's an annoying thing and will be good to have a solution, but I see some issues: 

* when registering an operation in logic we try to be UI agnostic and CloseForm is kind of crossing the line. Think that operations can be executed contextually or in processes. Not a deal breaker but something to have in mind. 

* in Web Applications, closing the form only works in pop-up. What should be the behaviour on full screen? For delete we go back to search, but with no particular filters. Not sure if this default behaviour will be good enough for more popular operations like Save. 

* in what kind of OperationServer you typically  want to close popup? In save? 

I would love to discuss the topic and get some fresh insight about it.

**Comment by solaimanjdn** [comment]
Hi
You are right, FlowDirection  and Unicode SQL are for RTL localization, are they make issue in other places?

default value in generated SQL does not work for string properties when there is space in value, I fixed it in new [commit](https://github.com/signumsoftware/framework/pull/154/commits/32c33ed64461c640a8ee6dafcf47e653b635cfa5)

Yes, I want to use it in save operation, for now I implemented this functionality in WPF and have no idea in Web,  and also I couldn't figure out better way to implement it

**Comment by olmobrutall** [comment]
You know the concept of OperationSettings? Is where you customize the UI behaviour of operations. I think AutoClose will make more sense there, if any. 

Other previous attempts have been to duplicate the button:  Save, and Save and Close. The problem then is what you do for other operations, like authorize, cancel, etc...

Maybe auto closing when pressing Shift, or Alt  and clicking on an operation could make sense.

Where are you planning to use the feature? In what kind of operations?

**Comment by solaimanjdn** [comment]
I want to close form in Save operation

**Comment by olmobrutall** [comment]
I don't see it as a solution that is clean enough, because then you can not save without closing and is not expected by the user in any way whether an operation will close or not.

Could you at least move it to OperationSettings in windows to experiment there?

Thanks

**Comment by solaimanjdn** [comment]
implemented in OperationSettings and works for me:)

**Comment by olmobrutall** [comment]
You even clean up the old commits! Thanks for the PR :)

**Pull request merged**
