### PR TITLE
fix Unit translation

### PR DESCRIPTION
**Pull request by MehdyKarimpour**

### CODE REVIEW

**Comment by MehdyKarimpour** [comment]
Because unit translation did not work for ValueSearchControlLine with the previous code. 
I said you and you wrote me that you can check  EntityPropertyToken.cs file. I checked and saw the code for Unit that did not consider the translation.
After changing the code, ValueSearchControlLine works fine and shows translated unit.

**Comment by olmobrutall** [comment]
I think I know now where is the problem. 

Check if it works if you add the translation in ColumnDescriptionTS and remove it in EntityPropertyToken

**Comment by MehdyKarimpour** [comment]
Ok

**Comment by MehdyKarimpour** [comment]
Works fine. 👍

**Pull request merged**
