### PR TITLE
fix LiteAutocompleteConfig.renderItem

### PR DESCRIPTION
**Pull request by mapacheL**

### CODE REVIEW

**Comment by mapacheL** [comment]
I've just updated. The bug happens because for some reason item.toStr is undefined on runtime, so use  .entity.toStr as fallback.

**Comment by olmobrutall** [comment]
Now that I think of it, I think the best is to use getToString in Reflection.tsx, it does always the right thing (including for symbols, that need to be translated)

**Comment by mapacheL** [comment]
In Reflection.ts there's no getToString, I've found one getToString function in Entitites.ts, but throws an error if used at this point

**Comment by olmobrutall** [comment]
What for an error? Is item really a lite at this point? If so it should work...

**Comment by olmobrutall** [comment]
Now is good!

**Pull request merged**
