### PR TITLE
implement window container

### PR DESCRIPTION
**Pull request by solaimanjdn**
this is experimental way to embed finder window in any container
there is simple tabbed main window implemented [here](https://github.com/solaimanjdn/southwind)

### CODE REVIEW

**Comment by olmobrutall** [comment]
Hi @solaimanjdn!

Thanks for the pull request :)

However I don't understand what you trying to accomplish. 

The SearchWindow is already a very thin component that contains a SearchControl. It only adds a title and two buttons. I don't see any argument to split it again in two so you can use it in a tab component. 

In one project we create our own NavigatioManager that replaces the standard Navigator.Create by creating new tabs in a global tab container instead of opening windows. Is this what you trying to accomplish?

Cheers! 



If you want to use it in a tab component you can

**Comment by olmobrutall** [comment]
Hi @solaimanjdn, 

Any news on this? Did u were able to move forward. 

I'll like to close or merge this PR.

**Comment by solaimanjdn** [comment]
Hi
I removed old commit and followed your instructions, but now i changed visibility of some properties that i used in my code

**Comment by olmobrutall** [comment]
Merged :)

... at the end every method is public. Is a matter of time :)

**Pull request merged**
