### PR TITLE
Only convert to or from UTC when needed

### PR DESCRIPTION
**Pull request by ghockx1p**

### CODE REVIEW

**Comment by ghockx1p** [comment]
Prevents ArgumentExceptions like these: "The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly. For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local. Parameter name: sourceTimeZone"

**Comment by olmobrutall** [comment]
Hi Geraldo, 

Where u storing local dates in entities in a UTC app?

**Comment by ghockx1p** [comment]
I'm not storing local dates. But in one WPF user control I need separate input for date (DateTimePicker) and time (TimePicker). The DateTime value needs to be converted to local before I can split the up. Then the DateTimeConverter of the DateTimePicker will try to convert once again. This causes the error.

**Comment by olmobrutall** [comment]
Makes sense! Thanks.

**Pull request merged**
